### PR TITLE
Kube client update

### PR DESCRIPTION
**Pull request by grs**
This is a rebase of https://github.com/skupperproject/skupper/pull/996 with conflicts resolved

### CODE REVIEW

**Comment by grs** [comment]
@mathianasj I rebased your patches so we can merge them in, is this ok with you?

**Review by nluaces — APPROVED** [review]

**Comment by mathianasj** [comment]
@grs That works for me proceed when ready

**Comment by mathianasj** [comment]
@grs when do we think this will be merged so i can do the feature request i have?

**Review by granzoto — APPROVED** [review]
Tested against OCP 3.11
Approved

**Pull request merged**
