### PR TITLE
Add HEY tests for HTTP

### PR DESCRIPTION
**Pull request by granzoto**
Add HEY tests for HTTP1

Signed-off-by: Renato Granzoto <rgranzot@redhat.com>

### CODE REVIEW

**Review by fgiorgetti — APPROVED** [review]

**Review by grs — APPROVED** [review]
Looks ok to me. Do we know what happened withe the first CI failure? Seemed like the hey tests did not complete?

**Comment by granzoto** [comment]
@grs yes, it has failed because the image was not public.  It is public now

**Comment by grs** [comment]
Greatm thanks for confirming! Nice work! :shipit:

**Review by ajssmith — APPROVED** [review]
lgtm, nice job

**Pull request merged**
