### PR TITLE
[v2] pkg/kube/site issues logs via slog

### LINKED ISSUE #1692: [v2] update pkg/kube/site to issue logs via slog
In v2, update pkg/kube/site to issue logs via slog.

### PR DESCRIPTION
**Pull request by Karen-Schoener**
Updating pkg/kube/site to issue logs via slog.

Fixes #1692

Below, I've pasted the info logs that the skupper-controller issued while I ran the hello-world steps:
  - create a site in east, west.
  - link sites
  - create listener, connector
  - delete listener, connector.  delete accessgrant, accesstoken.  delete sites. 

```
kubectl -n skupper logs skupper-controller-67f6c9f66b-s6m8z --follow | grep "component=kube.site"
time=2024-10-01T14:57:58.603Z level=INFO msg="Initialising site" component=kube.site.site namespace=west name=west
time=2024-10-01T14:57:58.610Z level=INFO msg="Config map created successfully" component=kube.site.site namespace=west group=skupper-router
time=2024-10-01T14:57:58.610Z level=INFO msg="Router config created for site" component=kube.site.site namespace=west name=west
time=2024-10-01T14:58:02.448Z level=INFO msg="Initialising site" component=kube.site.site namespace=east name=east
time=2024-10-01T14:58:02.455Z level=INFO msg="Config map created successfully" component=kube.site.site namespace=east group=skupper-router
time=2024-10-01T14:58:02.455Z level=INFO msg="Router config created for site" component=kube.site.site namespace=east name=east
time=2024-10-01T14:58:49.187Z level=INFO msg="Connecting site using token" component=kube.site.site namespace=east token=my-token
time=2024-10-01T14:59:11.369Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.369Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.369Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.372Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.372Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.372Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.391Z level=INFO msg="INFO No pods available for target selection component=kube.site.bindings id=\"Connector backend/east\""
time=2024-10-01T14:59:11.396Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.396Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.396Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.400Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.400Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.400Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.404Z level=INFO msg="INFO No pods available for target selection component=kube.site.bindings id=\"Connector backend/east\""
time=2024-10-01T14:59:11.404Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.404Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.404Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.407Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-7d5m5 connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.407Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-zct5z connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.407Z level=INFO msg="INFO Pod selected for connector component=kube.site.bindings pod=backend-8485574c8b-2qr8c connector=\"Connector backend/east\""
time=2024-10-01T14:59:11.411Z level=INFO msg="INFO No pods available for target selection component=kube.site.bindings id=\"Connector backend/east\""
time=2024-10-01T15:00:24.090Z level=INFO msg="Deleting site" component=kube.site.site namespace=west name=west
time=2024-10-01T15:00:27.647Z level=INFO msg="Deleting site" component=kube.site.site namespace=east name=east

```

### CODE REVIEW

**Comment by Karen-Schoener** [comment]
@grs @c-kruse when you get a chance, it's be great to hear your feedback on this PR.  

I'll be curious to hear if you are happy with the 'component' string that is issued.

Also, in pkg/kube/site/bindings.go, I created a bindings_logger variable (instead of adding a logger field to objects in bindings.go).  I will be curious to hear if you think this is ok.

Thanks very much...  Karen

**Comment by Karen-Schoener** [comment]
> Looks good to me @Karen-Schoener!
> 
> Maybe logging practices would be a good topic to raise at a community meeting or as part of an ADR as we being to go through and retofit these packages. I had started using slog + the 'component' pattern without really fielding any input from the group, it would be good to formalize these.
> 
> Also of note, it looks like we've got some Debug level logs in there but as I understand, possibly incorrectly, the default handler uses the log level INFO - so there may not be any way to enable those without a code change. (I am also guilty of adding these questionably functional debug statements)

Thanks very much for the feedback, @c-kruse.

Btw, in a separate PR, I plan to add the ability to configure the skupper-controller log level.  
A request has been made to be able to change the log level dynamically.
I just opened a ticket to track this work item (ability to configure log level): https://github.com/skupperproject/skupper/issues/1698

As I worked on these changes, I had a question on:
  - Should the component be the module name, or should the component include the golang file name.  
     So, for this PR, I wondered: should the component be: the shorter string: kube.site (vs kube.site.site or kube.site.bindings)?
     I went with having the component include the golang file name.
     I will be curious if there is feedback on this...
  
Thanks again!

**Review by grs — APPROVED** [review]
Looks fine to me. I need to think some more on what 'component' names would most make sense for users, but your changes are improvements and we should go ahead with them and improve on the component names in a subsequent PR.

**Review by c-kruse — APPROVED** [review]

**Review by ajssmith — APPROVED** [review]
lgtm

**Pull request merged**
