### PR TITLE
add console url to inspect response

### PR DESCRIPTION
**Pull request by ajssmith**
In the spirit of #147, adding url to inspect makes it simpler to access the console.

### CODE REVIEW

**Comment by ajssmith** [comment]
Yes, 'skupper status' will trigger

**Comment by pwright** [comment]
just cli? eg `kubectl get configmaps skupper-site -o yaml`?

**Comment by grs** [comment]
> just cli? eg `kubectl get configmaps skupper-site -o yaml`?

I think just cli is good enough for now. We need to think through a general approach for conveying information from the skupper system to the user on the command line when the skupper cli is not in use. That is a bigger task and should not hold up improvement on the cli though.

**Comment by pwright** [comment]
@grs that makes sense, but created an issue to track the differences twixt cli and yaml

**Pull request merged**
