### PR TITLE
Fix handling of enable-console option

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Comment by grs** [comment]
> One comment or suggestion would be to allow modifying `--enable-console` value through `SiteConfigUpdate` so users can enable the console on an already initialized namespace, if needed. If you think it is a good idea, I can raise an issue.

I agree that would be a useful enhancement. (The intention is eventually that all aspects can be updated)

**Comment by fgiorgetti** [comment]
> > One comment or suggestion would be to allow modifying `--enable-console` value through `SiteConfigUpdate` so users can enable the console on an already initialized namespace, if needed. If you think it is a good idea, I can raise an issue.
> 
> I agree that would be a useful enhancement. (The intention is eventually that all aspects can be updated)

And I believe this is going to be addressed by an existing issue #58. Thank you!

**Comment by ajssmith** [comment]
iiuc, intent is the console should be enabled by default, should default be changed from false to true in cmd/skupper/skupper.go?

Otherwise, user will need to '--enable-console on init'

**Comment by grs** [comment]
> iiuc, intent is the console should be enabled by default, should default be changed from false to true in cmd/skupper/skupper.go?

Yes! Had not realised that it was off by default there. Previously the flag was not properly honoured so would always be on regardless. With this fix though we do need to change the default which I have now done.

Well spotted!

**Review by ajssmith — APPROVED** [review]
lgtm

built and tried true/false on OpenShift and minikube.

**Pull request merged**
