### PR TITLE
remove stale code

### PR DESCRIPTION
**Pull request by grs**
This removes code from v1 that is no longer used in v2. Shout if you see anything you think should be kept.

### CODE REVIEW

**Review by nluaces — APPROVED** [review]
Looks good to me!

**Comment by nluaces** [comment]
I suggest to remove integration tests too, they rely on deleted code.

**Review by fgiorgetti — APPROVED** [review]
A new beginning.

**Review by c-kruse — APPROVED** [review]
:tada:

**Comment by c-kruse** [comment]
`go mod tidy` may be in order - I bet we've removed a few deps.

**Review by ajssmith — APPROVED** [review]
huzzah

**Pull request merged**
