### PR TITLE
add receiver for flow address

### PR DESCRIPTION
**Pull request by ajssmith**
required for:

https://github.com/skupperproject/skupper-router/pull/930

### CODE REVIEW

**Review by nluaces — APPROVED** [review]
Looks good to me; just to confirm, the console is the one that will filter by the `.flows` suffix in the beacon address, right?

**Review by grs — APPROVED** [review]
Is there any issue with versioning here? e.g. if the local router is from before this change? or if there are older sites in the network?

**Comment by ajssmith** [comment]
@grs for downrev routers, the flow records should arrive on the original address. iiuc, adding the new flow address should not impact collection.

**Review by fgiorgetti — APPROVED** [review]
Looks good to me.

**Pull request merged**
