### PR TITLE
Include Skupper v2 CLI specification

### PR DESCRIPTION
**Pull request by nluaces**
Original source: https://github.com/ssorj/skupper-cli-spec/tree/main

### CODE REVIEW

**Comment by fgiorgetti** [comment]
Should this PR be opened against the v2 branch instead of main ?

**Comment by fgiorgetti** [comment]
> We are merging ADRs that are V2 related in main, should we treat this one differently?

I think that for ADRs, it should be ok. But my impression is that it might be confusing to
people looking at `site create` in the main branch.

**Comment by ajssmith** [comment]
I would also lean to placing in v2 branch for now...thnx

**Comment by nluaces** [comment]
I need to close this pr to no introduce any other commit from main.

**Pull request closed without merging**
