### PR TITLE
Fixes for site-controller

### LINKED ISSUE #378: Bug: Skupper Site Controller fails to update router deployments due to invalid spec
When starting or updating router deployments, we see these errors crop up in the `skupper-site-controller:v0.4.0` logs relating to the skupper-site-token, in this case, named `cloud-connection-token`

```
2021/01/14 18:12:56 Connecting site in default using token cloud-connection-token
E0114 18:12:56.219048       1 controller.go:176] Failed to update skupper-router deployment: Deployment.apps "skupper-router" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "cloud-connection-token", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/qpid-dispatch-certs/cloud-connection-token-profile/": must be unique]
2021/01/14 18:12:56 Connecting site in monitoring using token skupper
E0114 18:12:56.323870       1 controller.go:176] Failed to update skupper-router deployment: Deployment.apps "skupper-router" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "skupper", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/qpid-dispatch-certs/skupper-profile/": must be unique]
2021/01/14 18:14:42 Connecting site in default using token cloud-connection-token
E0114 18:14:42.109303       1 controller.go:176] Failed to update skupper-router deployment: Deployment.apps "skupper-router" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "cloud-connection-token", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/qpid-dispatch-certs/cloud-connection-token-profile/": must be unique]
2021/01/14 18:16:28 Initialising skupper site ...
Secret already exists:  skupper-amqps
Secret already exists:  skupper
Secret already exists:  skupper-console-users
2021/01/14 18:16:30 Skupper site initialised
2021/01/14 18:16:30 Checking tokens...
2021/01/14 18:16:30 Checking token requests...
2021/01/14 18:16:30 Done.
2021/01/14 18:16:30 Connecting site in default using token cloud-connection-token
E0114 18:16:30.865034       1 controller.go:176] Failed to update skupper-router deployment: Deployment.apps "skupper-router" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "cloud-connection-token", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/qpid-dispatch-certs/cloud-connection-token-profile/": must be unique]
2021/01/14 18:16:30 Connecting site in monitoring using token skupper
E0114 18:16:31.110605       1 controller.go:176] Failed to update skupper-router deployment: Deployment.apps "skupper-router" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "skupper", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/etc/qpid-dispatch-certs/skupper-profile/": must be unique]
```

### PR DESCRIPTION
**Pull request by grs**
* use correct namespace when trying to inspect a site
* check whether connector already exists when creating it

Should fix #378

### CODE REVIEW

**Comment by ajssmith** [comment]
Suggest that images in site-controller deploy yaml's be updated with the patch as version is not currently specified and old images are being pulled down

**Comment by grs** [comment]
The yaml is updated on release branches (though so far it has been to a floating minor, whereas I think we should now update the site-controller even for patch releases). I can push an update now to 0.4 that moves the yaml to 0.4.2 explicitly if desired, but that wouldn't pull in this change which has yet to be released (currently targeting 0.5.0 though we could also backport it as 0.4.3 if desired, at which point updating the yaml would make sense).

**Comment by grs** [comment]
Another point is that really the release process should move the latest floating to the most recent one. I have done that manually now both for site-controller and service-controller.

Once the update mechanism (pr #380) is released (again 0.5.0 is current target for that), then updating the site controller image will automatically update the sites it controls also.

**Review by ajssmith — APPROVED** [review]
lgtm

I tried both current and all namespace deployments. Verified correct namespace used for 'all' site-controller. Locally modified cluster test to check duplicate connector.

**Comment by grs** [comment]
Thanks @ajssmith !

**Pull request merged**
