### PR TITLE
Move edge connectivity test to integration(#305)

### PR DESCRIPTION
**Pull request by mgoulish**
* Introduce edge_connectivity directory and
  two files.

* Look at how many interior nodes the single
  edge node can see, both directly and
  indirectly. Make sure the count is correct.

### CODE REVIEW

**Comment by mgoulish** [comment]
I am having a timeout problem that I need some help with. The final test -- number 5 in the list -- runs fine if I run it alone, but always times out at 10m0s if I run all of them. I have changed all the timeouts I can find, but it keeps happening -- always at 10m0s.

**Comment by mgoulish** [comment]
Aha! I see how to solve the timeout problem.
I could not find it in the code, because it is not in the code.
It works if I run it this way:
go test -v -count=1 -tags integration ./test/integration/edge_connectivity **-timeout 15m**

Is there some way that we can get it to run this way in the automated testing?

**Comment by fgiorgetti** [comment]
> Aha! I see how to solve the timeout problem.
> I could not find it in the code, because it is not in the code.
> It works if I run it this way:
> go test -v -count=1 -tags integration ./test/integration/edge_connectivity **-timeout 15m**
> 
> Is there some way that we can get it to run this way in the automated testing?

@mgoulish in Circle CI it's been executed as:
`go test -tags=integration -timeout=60m -v -p 1 ./test/integration/...`

Do you think it is OK as is?

**Comment by mgoulish** [comment]
Yes, -timeout=60m seems fine to me, I was just running it by hand with the
default -timeout=10m, and it wasn't enough.

**Comment by mgoulish** [comment]
Closing this one in favor of #333

**Pull request closed without merging**
