### PR TITLE
CRD revisions

### PR DESCRIPTION
**Pull request by grs**
* change version to v2alpha1
* use settings consistently for all resources
* add message field to status and use existing status field as machine readable state description (Ready, Pending or Error)

### CODE REVIEW

**Comment by fgiorgetti** [comment]
The following yaml files are adding ownerReferences using `v1alpha1`:
* `pkg/kube/site/resources/skupper-router-deployment.yaml`
* `pkg/kube/site/resources/skupper-router-local-service.yaml`

**Comment by grs** [comment]
> The following yaml files are adding ownerReferences using `v1alpha1`:
> 
>     * `pkg/kube/site/resources/skupper-router-deployment.yaml`
> 
>     * `pkg/kube/site/resources/skupper-router-local-service.yaml`

Well spotted! Fixed now.

**Review by c-kruse — COMMENTED** [review]
./cmd/network-console-collector/* has a different  "v1alpha1" (the collector api version.) Could you reset everything under there and patch the yaml resources?

i.e.

```
find ./cmd/network-console-collector/resources/ \
-name "*.yaml" \
-exec sed -i \
    's/^apiVersion: skupper.io\/v1alpha1/apiVersion: skupper.io\/v2alpha1/' \
    {} ";"
```

**Comment by grs** [comment]
> ./cmd/network-console-collector/* has a different "v1alpha1" (the collector api version.) Could you reset everything under there and patch the yaml resources?

Oops, sorry! Done now.

**Review by fgiorgetti — APPROVED** [review]

**Review by lynnemorrison — APPROVED** [review]

**Review by c-kruse — APPROVED** [review]

**Review by ajssmith — APPROVED** [review]

**Review by ssorj — APPROVED** [review]

**Pull request merged**
