### PR TITLE
Router scaling

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Review by nluaces — APPROVED** [review]

**Review by ajssmith — COMMENTED** [review]
An observation is that prior to this change, qdr connections were interpreted as "sites".  

With the change, for example, two sites with --routers 3 will report the following status

"It is connected to 5 other sites (3 indirectly)"

**Comment by grs** [comment]
@ajssmith Thanks! I've fixed that now.

**Review by ajssmith — APPROVED** [review]
lgtm, thanks!

**Review by fgiorgetti — COMMENTED** [review]
LGTM

**Pull request merged**
