### PR TITLE
fix original service restoration

### PR DESCRIPTION
**Pull request by qb0C80aE**
Issue: #[1191](https://github.com/skupperproject/skupper/issues/1191)

As suggested, I also considered iterating through the return value if `GetOriginalTargetPorts()`.
However, its type is map[int]int, so the order is unpredictable.
Since I thought it's better to preserve the previous port names as much as possible, I took the way iterating through the current ports.

```
During the iteration:
1. If the port value exists as a key in the original port map, the port's name is kept unchanged and restored the TargetPort using the value.
2. If the port value doesn't exist as a key in the original port map, there is no need to restore it.

After the iteration:
3. The map keys that haven't been referenced up to this point need to be restored as port entries.
```

The reason why step 2. and 3. above might be necessary is:

Suppose the original service `app1` has only one port, `80:8080`.

[I] If there is no `--port` specified on `expose service`, and `app1` is exposed with the same name as address, the number of entries in service's `ports` and the port values inside that exactly matchs the content of service's `originalTargetPort` annotation. In this case, processing step 1. above is enough.
```
ex.
run `skupper expose service app1 --address app1`
then run `skupper unexpose service app1.site1 --address app1`
```

[2] If `--port` is specified on `expose service`, or `create service`, with the same name address,
the number of ports and port values can be different from the original ones in `app1` (I'm not sure whether accepting this is intended behavior or not).
In this case, steps 2. and 3. become necessary.
ex. 
```
run `skupper expose service app1 --address app1 --port 11111 22222 ...`
then run `skupper unexpose service app1.site1 --address app1`

or

run `skupper service create app1 11111 22222 ...`
then run `skupper service delete app1`
```

In steps 2. and 3., the port names and the order of entries cannot be restored anyway.

### CODE REVIEW

**Review by grs — APPROVED** [review]

**Review by nluaces — APPROVED** [review]

**Comment by fgiorgetti** [comment]
@qb0C80aE would you mind rebasing (on main) and updating this PR?

**Comment by qb0C80aE** [comment]
not at all, I've rebased it on main.

**Comment by qb0C80aE** [comment]
@fgiorgetti @grs @nluaces Thank you for your time!

**Comment by grs** [comment]
Thank you @qb0C80aE !

**Pull request merged**
