### PR TITLE
skupper init fixes for rootful podman

### LINKED ISSUE #1465: skupper init for rootful podman returns: Unable to create startup service - SystemD is not enabled at user level
**Describe the bug**
Attempting to init a podman site as root fails due to:
Unable to create startup service - SystemD is not enabled at user level

Issue observed while addressing skupper ticket #1401:

> skupper init for rootful podman should try /run/podman/podman.sock #1401
> https://github.com/skupperproject/skupper/issues/1401

**Environment details**
 - Skupper CLI: 1.6.0

**How To Reproduce**

Run with patch for ticket skupper ticket #1401.

As root user, run the following:
```
# ./skupper --platform podman init
Unable to create startup service - SystemD is not enabled at user level
The startup scripts: start-podman.sh and stop-podman.sh are available at /root/.local/share/skupper
Waiting for status...
Skupper status is not loaded yet.
Skupper is now installed for user 'root'.  Use 'skupper status' to get more information.
```

### PR DESCRIPTION
**Pull request by Karen-Schoener**
When a skupper site (podman) is initialized, the Skupper CLI checks whether user is root before it creates a systemd service as user level only.

Fixes #1465

### CODE REVIEW

**Comment by Karen-Schoener** [comment]
Tested locally as root:
```
[root@fedora skupper]#  ./skupper --platform podman init
Waiting for status...
Skupper is now installed for user 'root'.  Use 'skupper status' to get more information.

[root@fedora skupper]# podman ps
CONTAINER ID  IMAGE                                   COMMAND               CREATED         STATUS         PORTS                                               NAMES
0447b737d2df  quay.io/skupper/skupper-router:main     /home/skrouterd/b...  19 seconds ago  Up 19 seconds  0.0.0.0:45671->45671/tcp, 0.0.0.0:55671->55671/tcp  skupper-router
17f7c684c2c0  quay.io/skupper/controller-podman:main  /app/controller-p...  18 seconds ago  Up 18 seconds                                                      skupper-controller-podman

[root@fedora skupper]#  ./skupper --platform podman delete
Skupper is now removed for user 'root'.
```

Tested locally as non-root:
```
[kschoener@fedora skupper]$ ./skupper --platform podman init
It is recommended to enable lingering for kschoener, otherwise Skupper may not start on boot.
Waiting for status...
Skupper is now installed for user 'kschoener'.  Use 'skupper status' to get more information.

[kschoener@fedora skupper]$ podman ps
CONTAINER ID  IMAGE                                   COMMAND               CREATED         STATUS         PORTS                                               NAMES
4f822467a628  quay.io/skupper/skupper-router:main     /home/skrouterd/b...  20 seconds ago  Up 20 seconds  0.0.0.0:45671->45671/tcp, 0.0.0.0:55671->55671/tcp  skupper-router
513daf5f194a  quay.io/skupper/controller-podman:main  /app/controller-p...  19 seconds ago  Up 19 seconds                                                      skupper-controller-podman

[kschoener@fedora skupper]$ ./skupper --platform podman delete
Skupper is now removed for user 'kschoener'.
```

**Comment by fgiorgetti** [comment]
The location of the startup scripts cannot be the same we use for user scoped services (XDG_DATA_HOME),
as systemd cannot execute them under /root/. Maybe the scripts could be placed under `/usr/local/bin` ?

**Comment by fgiorgetti** [comment]
Another thing that is missing are the commands for  the Remove method. They are still only qualified with `--user`.

**Comment by Karen-Schoener** [comment]
> Another thing that is missing are the commands for the Remove method. They are still only qualified with `--user`.

Fixed.

**Review by fgiorgetti — APPROVED** [review]

**Review by grs — APPROVED** [review]

**Review by nluaces — APPROVED** [review]

**Pull request merged**
