### PR TITLE
add support for mac on arm64

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Comment by grs** [comment]
I believe this is all we need to produce an arm64 cli build for macs as requested in issue #888 ?

**Comment by nluaces** [comment]
This is old (2020) issue:

> The problem is that darwin-arm64 does not support internal linking, which means that Go has to invoke the C linker, which means that you need to have a cross-linker from your host system to darwin-arm64. The Go linker is invoking the C linker, but it's not a cross-linker, so it fails.

source: https://github.com/golang/go/issues/39033

Is it possible that it has been fixed at this point?

**Comment by nluaces** [comment]
Never mind, Seems like it is fixed since 1.16:

> Darwin and iOS
> Go 1.16 adds support of 64-bit ARM architecture on macOS (also known as Apple Silicon) with GOOS=darwin, GOARCH=arm64. Like the darwin/amd64 port, the darwin/arm64 port supports cgo, internal and external linking, c-archive, c-shared, and pie build modes, and the race detector.

https://go.dev/doc/go1.16#darwin

**Review by nluaces — APPROVED** [review]

**Comment by grs** [comment]
Yes, I tried out the options and it built ok. Resulting binary seems to run ok also on Mac on M1.

**Review by fgiorgetti — APPROVED** [review]
I can't test, but it looks right to me.

**Pull request merged**
