### PR TITLE
do not overwrite unrecognised fields in router config entities

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Comment by grs** [comment]
Fixes skupperproject/skupper-router#1132

**Review by fgiorgetti — APPROVED** [review]
It seems to work fine.

**Review by gabordozsa — APPROVED** [review]
Looks good! 

Just one comment: this approach requires changes in the `skupper-router` code as well. Otherwise, `skupper-router` cannot find the parameters defined  in `extraFields` (so it will  still fallback to the default values). This PR is a partial fix for https://github.com/skupperproject/skupper-router/issues/1132

**Comment by grs** [comment]
> Just one comment: this approach requires changes in the `skupper-router` code as well. Otherwise, `skupper-router` cannot find the parameters defined in `extraFields` (so it will still fallback to the default values). 

The extraFields is purely an in memory holder for fields not explicitly named. The resulting config file which the router reads has the fields with their expected names in the entities as expected.

**Comment by gabordozsa** [comment]
> > Just one comment: this approach requires changes in the `skupper-router` code as well. Otherwise, `skupper-router` cannot find the parameters defined in `extraFields` (so it will still fallback to the default values).
> 
> The extraFields is purely an in memory holder for fields not explicitly named. The resulting config file which the router reads has the fields with their expected names in the entities as expected.

Okay, I got confused. I'm testing this in my local setup and the router still picks up the default value for `idleTimeoutSeconds`. It might be some problem in my test setup.

**Comment by gabordozsa** [comment]
> > > Just one comment: this approach requires changes in the `skupper-router` code as well. Otherwise, `skupper-router` cannot find the parameters defined in `extraFields` (so it will still fallback to the default values).
> > 
> > 
> > The extraFields is purely an in memory holder for fields not explicitly named. The resulting config file which the router reads has the fields with their expected names in the entities as expected.
> 
> Okay, I got confused. I'm testing this in my local setup and the router still picks up the default value for `idleTimeoutSeconds`. It might be some problem in my test setup.

It works for me now. I had a problem in my local setup. Sorry for the noise!

**Pull request merged**
