### PR TITLE
don't try to move claims for edge site on update

### PR DESCRIPTION
**Pull request by grs**
Without this fix, trying tp update a site where router-mode=edge results in an error `Error: services "skupper-router" not found`

### CODE REVIEW

**Review by nluaces — APPROVED** [review]

**Review by fgiorgetti — COMMENTED** [review]
There is a problem here.
The moveClaims is not just doing what it says.

It is also updating skupper-router role, adding extra permissions
needed by the collector lite. And without it, collector lite won't have
permissions to create the skupper-network-status configmap.

I believe we need to introduce an extra variable to control that separately from
the moveClaims.

**Comment by grs** [comment]
Good catch, I'll push an update.

**Comment by grs** [comment]
Fix pushed that ensures the role is updated for config-sync to be able to create the configmap and write the status.

**Review by fgiorgetti — APPROVED** [review]
LGTM

**Pull request merged**
